name: 'Download Godot'
description: 'Download Godot'
inputs:
  godot-version:
    description: 'Version of godot to download'
    required: true
    default: '4.3'
runs:
  using: 'composite'
  steps:
    - name: Download Godot
      uses: robinraju/release-downloader@v1
      with:
        repository: godotengine/godot
        tag: ${{ env.GODOT_VERSION }}-stable
        filename: Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
        extract: true
    - name: Rename Godot
      shell: bash
      run: |
        mv Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64 godot_stable_linux.x86_64
    - name: Make Godot Executable
      shell: bash
      run: |
        chmod +x godot_stable_linux.x86_64
